version: '3.8'

services:
  # TU MICROSERVICIO
  app-productos:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      # Aquí "inyectamos" la configuración de MySQL para producción
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/tiendadb?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password123
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver

  # LA BASE DE DATOS
  mysql-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: tiendadb
      MYSQL_ROOT_PASSWORD: password123
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: