# --- SERVER CONFIG ---
server.port=8080
spring.application.name=ms-productos

# --- DATABASE CONFIG (H2 default / MySQL docker) ---
spring.datasource.url=jdbc:h2:mem:tiendadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# --- CONSOLA H2 ---
spring.h2.console.enabled=true

# --- JPA / HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- CARGA DE DATOS AUTOMATICA (data.sql) ---
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# --- AJUSTE DOCKER (Variables de entorno) ---
# spring.datasource.url=${DB_URL}
# spring.datasource.username=${DB_USER}
# spring.datasource.password=${DB_PASSWORD}